name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore NuGet packages
      run: |
        cd exercise-1
        dotnet restore
        cd ../exercise-2
        dotnet restore

    - name: Build Solutions
      run: |
        cd exercise-1
        dotnet build --configuration Release
        cd ../exercise-2
        dotnet build --configuration Release
